services:
  ppt-generator:
    build: .
    container_name: ppt-generator
    restart: always

    env_file:
      - .env

    volumes:
      - ./templates:/app/templates:ro
      - ./generated_ppts:/app/generated_ppts
      - ./testppt.pptx:/app/testppt.pptx:ro

    ports:
      - "5010:5000"
